services:
  frontend-1:
    build:
      args:
        BUILD_MODE: dev
  backend-1:
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/api/produtos || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 90s
  frontend-2:
    build:
      args:
        BUILD_MODE: dev
  backend-2:
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/api/produtos || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 90s
